name: cellector
version: "1.0.0"
author: Haynes Heaton <whheaton@gmail.com>
about: genotype outlier detection for scRNAseq
args:
    - ref_matrix:
        long: ref
        short: r
        takes_value: true
        required: true
        help: ref.mtx matrix from vartrix
    - alt: 
        long: alt
        short: a
        takes_value: true
        required: true
        help: alt.mtx matrix from vartrix
    - barcodes:
        long: barcodes
        short: b
        takes_value: true
        required: true
        help: cell barcodes
    - min_alt:
        long: min_alt
        takes_value: true
        required: false
        help: minimum number of cells containing the alt allele for the variant to be used for clustering
    - min_ref:
        long: min_ref
        takes_value: true
        required: false
        help: minimum number of cells containing the ref allele for the variant to be used for clustering 
    - ground_truth:
        long: ground truth
        short: g
        required: false
        takes_value: true
        help: cell hashing assignments or other ground truth, first column barcodes second column assignment
