[package]
name = "cellector"
version = "1.0.0"
authors = ["wheaton5 <whheaton@gmail.com>"]

[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
hashbrown = "0.1"
rand = "0.7.0"
itertools = "*"
rayon = "*"
vcf = "*"
flate2 = "*"
csv = "1.1"
statrs = "0.16"
